### ISSUE TITLE
RuntimeError: expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by StardustandRain** [silent-chen/DGE#14]
Traceback (most recent call last):
  File "launch.py", line 250, in <module>
    main(args, extras)
  File "launch.py", line 193, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 962, in _run
    call._call_lightning_module_hook(self, "on_fit_start")
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/invismile/dqx/DGE-main/threestudio/systems/DGE.py", line 604, in on_fit_start
    self.render_all_view(cache_name="origin_render")
  File "/home/invismile/dqx/DGE-main/threestudio/systems/DGE.py", line 255, in render_all_view
    out = self(cur_batch)["comp_rgb"]
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/invismile/dqx/DGE-main/threestudio/systems/DGE.py", line 181, in forward
    render_pkg = render(cam, self.gaussian, self.pipe, renderbackground)
  File "/home/invismile/dqx/DGE-main/gaussiansplatting/gaussian_renderer/__init__.py", line 131, in render
    rendered_image, radii, depth = rasterizer(
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 299, in forward
    return rasterize_gaussians(
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 37, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/invismile/anaconda3/envs/gaussian_splattinf/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 117, in forward
    ) = _C.rasterize_gaussians(*args)
RuntimeError: expected scalar type Float but found BFloat16

**Comment by Jeasco** [comment]
I have the same error, didi you solve it?

**Comment by MandyXie** [comment]
I got the same issue, and making the following change solved it:
./gaussiansplatting/scene/camera.py, in line 94, convert self.full_proj_transform to float:
self.full_proj_transform = (self.world_view_transform.unsqueeze(0).bmm(self.projection_matrix.unsqueeze(0))).squeeze(0).float()

**Comment by dtqtdl** [comment]
@MandyXie It worked for me. thx

**Comment by hhe-git** [comment]
@MandyXie love you bro
